#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- block:
    - name: Install dependencies
      zypper:
        name: python2-pycrypto
      become: yes

    - name: Install ansible-lint
      pip:
        name: 'ansible-lint==2.1.3'
        virtualenv: '{{ lint_venv }}'
        virtualenv_site_packages: true

    - name: Install Ardana linting rules
      synchronize:
        delete: true
        src: lint-rules
        dest: "{{ lint_venv }}/lint-rules"

    - name: Create a temporary directory
      command: mktemp -d
      register: _temp_path

    - name: Make a copy of "{{ lint_path }}"
      synchronize:
        src: '{{ lint_path }}'
        dest: '{{ _temp_path.stdout }}'
      delegate_to: "{{ inventory_hostname }}"

    - name: Find ansible files under "{{ _temp_path.stdout }}"
      command: >
        find "{{ _temp_path.stdout }}" -type f
        -name _ardana-base*yml -or -name client*yml -or
        -name *ceilometer*.yml -or -name *FND-AP2*.yml -or
        -name *FND-CLU*.yml -or -name *glance*.yml -or
        -name *heat*.yml -or -name *magnum*.yml -or
        -name *monasca-transform*.yml -or -name *nova*.yml -or
        -name *percona*.yml -or -name *rabbitmq*.yml -or
        -name *spark*.yml -or -name *tls*.yml
      register: _lint_files
      #TODO: run on all yml files. The current file list is copied from
      # ardana-dev-tools, and any other files are not yet expected to pass linting.
      failed_when: len(_lint_files) == 0
      # Fail if no files were found

    - name: Run ansible-lint on the files found
      command: "{{ lint_venv }}/bin/ansible-lint {{ lint_params }} {{ _lint_files.stdout }}"

  always:
    - name: Cleanup temporary copy
      file:
        path: "{{ _temp_path.stdout }}"
        state: absent
      when: _temp_path is defined

    - name: Remove dependencies
      zypper:
        name: python2-pycrypto
        state: absent
