#!/bin/sh
n=$1
if [ -z "$n" ] ; then
    echo "usage: $0 <vmname> [ flavor ]"
    exit 1
fi

if [[ "$n" != cleanvm ]] ; then
    echo "bad VM name"
    exit 2
fi

flavor=$2

p=/mnt/ssd/images/

if ! [ -f $p/$flavor.img -o -f $p/$flavor.qcow2 ]; then
    echo "Bad Flavor name: \"$flavor\""
    exit 2
fi

virsh destroy $n
if [[ -e /dev/vg0/$n-data ]] ; then
    dd if=/dev/zero of=/dev/vg0/$n-data count=16
fi
if [ -e $p/$flavor.qcow2 ] ; then
    qemu-img create -f qcow2 -o backing_file=$p/$flavor.qcow2 /dev/vg0/$n
else
    exit 3
fi

setfacl -m jenkins:r "/dev/vg0/$n"
virsh start "$n"

