#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- import_playbook: _create-vcloud-inventory.yml

- name: Collect list of installed packages in all nodes
  hosts: "{{ ardana_env }}, cloud_virt_hosts"
  remote_user: root
  gather_facts: True
  vars:
    task: "deploy"
    state: "default"
    ansible_ssh_common_args: >
      -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o
      StrictHostKeyChecking=no -W %h:%p -q root@{{ hostvars[ardana_env].ansible_host }}'
      -o ControlPath='~/.ansible/cp/{{ ardana_env }}-%r@%h:%p'

  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when: rc_notify

  tasks:
    - block:
        # FIXME this is for testing since we don't have maintupdate jobs
        - name: FIXME Inject a package
          zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "iftop"
          when: "'after_update' in state"

        - name: Ensure "rpms" artifacts dir exists
          file:
            path: "~/rpms"
            state: "directory"

        - name: Collect list of installed packages in plaintext
          shell: |
            rpm -qa | sort > ~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.txt
          args:
            warn: False
            creates: "~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.txt"

        - name: Collect list of installed packages in yaml
          shell: |
            rpm -qa --qf "%{NAME}:\n  version: %{VERSION}\n  release: %{RELEASE}\n  disturl: %{DISTURL}\n" \
            | perl -pe 'chomp;$_.=($.%4)?"\n":"\0"' | sort -z -t' ' -k1 | tr '\0' '\n' \
            > ~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.yaml
          args:
            warn: False
            creates: "~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.yaml"

        - name: Store lists of installed packages from nodes on "{{ ardana_env }}"
          fetch:
            src: "{{ item }}"
            dest: "{{ item }}"
          with_items:
            - "~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.txt"
            - "~/rpms/rpms_{{ inventory_hostname }}_{{ state }}.yaml"
          when: "'cloud_virt_hosts' not in group_names"

      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."

      always:
        - include_role:
            name: jenkins_artifacts
          vars:
            jenkins_artifacts_to_collect:
              - src: "~/rpms"
          when: lookup("env", "WORKSPACE")
