---

- name: Run Crowbar tests and collect results
  hosts: "{{ ardana_env }}"
  remote_user: root
  gather_facts: True
  vars:
    task: "tempest"
    tempest_results_subunit: "~/tempest.subunit.log"
    subunit_xml_results: "~/testr_crowbar.xml"
    subunit_html_results: "~/testr_crowbar.html"

  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when: rc_notify

  tasks:
    - block:
        - name: Crowbar log stream at
          debug:
            msg: "http://{{ ansible_host }}:9091/"

        - name: Install package dependencies
          zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "python-setuptools"
            - "python-os-testr" # includes subunit2html.py
            - "python-python-subunit"

        - name: Ensure leap repo for python-junitxml is in place
          zypper_repository:
            repo: "http://download.opensuse.org/distribution/leap/\
              {{ (ansible_distribution_major_version|int > 12) | ternary(ansible_distribution_major_version, ansible_distribution_major_version|int + 30) }}\
              .{{ ansible_distribution_release }}/repo/oss/"
            name: leap
            state: present
            disable_gpg_check: yes
            runrefresh: yes

        - name: Install python-junitxml
          zypper:
            name: python-junitxml
            state: present

        - name: Remove leap repo for python-junitxml
          zypper_repository:
            name: leap
            state: absent
            runrefresh: yes

        - include_role:
            name: crowbar_setup
          vars:
            qa_crowbarsetup_cmd: onadmin_testsetup

      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
      always:

        - name: Generate xml subunit results
          shell: "subunit2junitxml {{ tempest_results_subunit }} > {{ subunit_xml_results }}"
          changed_when: false
          failed_when: false

        - name: Generate html subunit results
          shell: "subunit2html {{ tempest_results_subunit }} {{ subunit_html_results }}"
          changed_when: false
          failed_when: false

        - name: Get results from subunit
          command: "subunit-stats {{ tempest_results_subunit }}"
          failed_when: false
          register: _test_results

        - name: Process test results from subunit
          set_fact:
            tempest_test_results: "{{ tempest_test_results | default({}) | combine({item.split()[0] | lower: item.split()[-1]}) }}"
          when: "'tests' in item"
          loop: "{{ _test_results.stdout_lines }}"
          loop_control:
            label: "{{ item.split()[0] | lower }}: {{ item.split()[-1] }}"

        - include_role:
            name: jenkins_artifacts
          vars:
            jenkins_artifacts_to_collect:
              - src: "{{ admin_mkcloud_config_file }}"
              - src: "{{ qa_crowbarsetup_log }}"
              - src: "~/tempest.log"
              - src: "~/tempest.subunit.log"
              - src: "~/testr_crowbar.html"
              - src: "~/testr_crowbar.xml"
          when: lookup("env", "WORKSPACE")

  post_tasks:
      - include_role:
          name: rocketchat_notify
        vars:
          rc_action: "finished"
          rc_state: "{{ (_qa_crowbarsetup_result.rc > 0) | ternary('Failed', 'Success' )}}"
        when: rc_notify
