#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Check defined VMs
  virt:
    command: list_vms
  register: libvirt

- name: Ensure all VMs are powered off
  virt:
    state: destroyed
    name: "{{ item }}"
  loop: "{{ libvirt.list_vms }}"

- name: Ensure previous VM disk deleted
  file:
    dest: "{{ libvirt_vm_images_dir }}/{{ vm_name }}.qcow2"
    state: absent

- name: Copy fresh VM disk
  copy:
    src: "{{ libvirt_fresh_images_dir }}/{{ vm_name }}.qcow2"
    dest: "{{ libvirt_vm_images_dir }}/{{ vm_name }}.qcow2"
    remote_src: yes

- name: Start fresh VM
  virt:
    state: running
    name: "{{ vm_name }}"

- name: Wait until VM is reachable
  wait_for:
    port: 22
    host: "{{ hostvars[cloud_env].ansible_host }}"
    search_regex: OpenSSH
    delay: 10
