
---

cinder_disk_enabled: "{{ cinder_lvm_enabled }}"

swiftpac_disk_enabled: True

# Start value for the third octet for the generated subnet prefixes and also
# start of generated VLAN IDs for Ardana networks
gen_subnet_start: 100
# Start value for the fourth octet for the generated server IP addresses
gen_ip_start: 100
# Gap to be left between the generated IP for the admin node and the rest of the nodes
gen_ip_gap: 1
