---
- name: Create ceph secrets
  template:
    src: "suse-define-ses-secrets-in-k8s.yml.j2"
    dest: "/tmp/ceph-secrets.yaml"
    mode: "0600"

- name: Create ceph storage class
  template:
    src: "suse-define-ses-storageclasses-in-k8s.yml.j2"
    dest: "/tmp/ceph-storage-classes.yaml"
    mode: "0600"

- name: "Apply ceph {{ item }}"
  command: "kubectl apply -f /tmp/ceph-{{ item }}.yaml --overwrite=true"
  with_items:
    - secrets
    - storage-classes
