#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Scenario parameters and default values
core_nodes: 1
lmm_nodes: 1
dbmq_nodes: 1
sles_computes: 3
rhel_computes: 0
swobj_devices: 3

scenario:
  name: standard
  cloud_name: standard
  description: >
    Standard split scenario with all services enabled, standalone CLM node, {{ core_nodes }} OpenStack core nodes,
    {{ dbmq_nodes }} database nodes, {{ lmm_nodes }} LMM nodes, {{ sles_computes }} SLES compute nodes and
    {{ rhel_computes }} RHEL compute nodes.
  mml_enabled: True
  audit_enabled: False
  ses_enabled: False
  use_cinder_volume_disk: False
  use_glance_cache_disk: False
  ntp_servers: "{{ ntp_servers }}"
  # generated by heat
  nameservers:
    - 192.168.245.3
    - 192.168.245.4
    - 192.168.245.2

  service_template: split
  network_template: standard
  disk_template: compact
  interface_template: standard
