#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

---

- import_playbook: _create-vcloud-inventory.yml

- name: Update cloud - crowbar
  hosts: "{{ cloud_env }}"
  remote_user: root
  gather_facts: True
  vars:
    task: "update"

  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when: rc_notify

  tasks:
    - block:
        # add MU repos
        - include_role:
            name: setup_zypper_repos
          when:
            - maint_updates_list | length

        - include_role:
            name: crowbar_update
            apply:
              delegate_to: "{{ target_host }}"
          vars:
            inventory_hostname: "{{ target_host }}"
          loop: "{{ [cloud_env]+groups['cloud_virt_hosts'] }}"
          loop_control:
            loop_var: target_host

        - include_role:
            name: reboot_node
          vars:
            reboot_target: deployer
          when:
            - update_after_deploy
            - reboot_after_deploy

        - include_role:
            name: crowbar_setup
          vars:
            qa_crowbarsetup_cmd: onadmin_rebootcloud
          when:
            - reboot_after_deploy
            - update_after_deploy

      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
      always:
        - include_role:
            name: jenkins_artifacts
          when: lookup("env", "WORKSPACE")
          vars:
            jenkins_artifacts_to_collect:
              - src: "{{ qa_crowbarsetup_log }}"

  post_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "finished"
        rc_state: "Success"
      when: rc_notify
