---

- name: Run Crowbar tests and collect results
  hosts: "{{ cloud_env }}"
  remote_user: root
  gather_facts: True
  vars:
    task: "tempest"


  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when: rc_notify

  tasks:
    - block:
        - name: Crowbar log stream at
          debug:
            msg: "http://{{ ansible_host }}:9091/"

        - include_role:
            name: crowbar_setup
          vars:
            qa_crowbarsetup_cmd: onadmin_testsetup

      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
      always:

        - include_role:
            name: tempest_results

        - include_role:
            name: jenkins_artifacts
          vars:
            jenkins_artifacts_to_collect:
              - src: "{{ admin_mkcloud_config_file }}"
              - src: "{{ qa_crowbarsetup_log }}"
              - src: "~/tempest.log"
              - src: "{{ tempest_results_subunit }}"
              - src: "{{ subunit_xml_results }}"
              - src: "{{ subunit_html_results }}"
          when: lookup("env", "WORKSPACE")

  post_tasks:
      - include_role:
          name: rocketchat_notify
        vars:
          rc_action: "finished"
          rc_state: "{{ (_qa_crowbarsetup_result.rc > 0) | ternary('Failed', 'Success' )}}"
        when: rc_notify
