#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- job:
    name: ardana-deploy
    description: |
      Deploy and run Ardana on a specified QE environment.
      Deployment will include cloud/sles maintenance updates when provided.
    wrappers:
      - workspace-cleanup:
          dirmatch: false
          include: .artifacts/**
      - ansicolor:
          colormap: xterm
      - build-name:
          name: '#${BUILD_NUMBER}-${qe_env}-${cloud_source}-${cloud_brand}-${ardana_input_model}'
    publishers:
      - archive:
          artifacts: .artifacts/**
          allow-empty: true
    scm:
      - git:
          branches:
            - ${ardana_deploy_branch}
          browser: auto
          url: ${ardana_deploy_repo}
    parameters:
      - label:
          name: qe_env
          description: Target QE environment to deploy
          matching-label: allCases
      - choice:
          name: cloud_source
          choices:
            - GM
            - devel
            - devel-staging
          description: From which release ardana will be installed.
      - choice:
          name: cloud_brand
          choices:
            - SUSE
            - HPE-Helion
          description: Cloud media brand.
      - choice:
          name: ardana_input_model
          choices:
            - entry-scale-kvm
            - entry-scale-swift
          description: Input model for ardana.
      - choice:
          name: clm_model
          choices:
            - standalone
            - integrated
          description: |
            standalone - one node dedicated for CLM
            integrated - the first controller node will also be used as a CLM node
      - string:
          name: controllers
          default: 3
          description: Number of nodes used as controller
      - string:
          name: sles_computes
          default: 2
          description: Number of SLES compute nodes
      - string:
          name: rhel_computes
          default: 0
          description: Number of RHEL compute nodes
      - bool:
          name: ses_enabled
          default: false
          description: Configure SES backend for glance, cinder, cinder-backup, nova and swift
      - string:
          name: cloud_maint_updates
          default: ''
          description: List of cloud maintenance update IDs separated by comma (eg. 7396,7487)
      - string:
          name: sles_maint_updates
          default: ''
          description: List of SLES maintenance update IDs separated by comma (eg. 7434,7435)
      - string:
          name: ardana_deploy_repo
          default: https://github.com/SUSE-Cloud/automation.git
          description: Git repository used for the deployment automation.
      - string:
          name: ardana_deploy_branch
          default: master
          description: Branch of the repository used for the deployment automation.
      - bool:
          name: rc_notify
          default: true
          description: Notify RocketChat when deployment starts/finishes.
    builders:
      - shell: |-
          #!/bin/bash

          export ANSIBLE_FORCE_COLOR=true

          source /opt/ansible/bin/activate
          cd scripts/jenkins/ardana/ansible
          ansible-playbook ardana-deploy.yml -e "qe_env=$qe_env cloud_source=$cloud_source \
            cloud_brand=$cloud_brand rc_notify=$rc_notify ardana_input_model=$ardana_input_model \
            cloud_maint_updates=$cloud_maint_updates sles_maint_updates=$sles_maint_updates \
            scenario_name=$ardana_input_model clm_model=$clm_model controllers=$controllers \
            sles_computes=$sles_computes rhel_computes=$rhel_computes ses_enabled=$ses_enabled""
