---

ardana_qe_test_venv_requires:
  - 'pymysql'
  - 'python-subunit'
  - 'selenium'
  - 'django'
  - 'nose'
  - 'tox'
  - 'stestr'
  - 'oslo_utils'
  - 'oslo_config'
  - 'xvfbwrapper'

ardana_qe_test_get_failed_cmd: "grep FAILED {{ ardana_qe_test_log }} || echo 'None'"
ardana_qe_test_get_results_cmds:
  passed: 'grep ok {{ ardana_qe_test_log }} | wc -l'
  failed: 'grep FAILED {{ ardana_qe_test_log }} | wc -l'
  ran: 'grep -e "FAILED\|ok" {{ ardana_qe_test_log }} | wc -l'