# The way remove_compute_node reports test results is one line per test so in this case we have
# 6 lines and any failures are reported as a non-zero value in column 11. This
# almost never happens and the more interesting value is the IOPS which in
# in column 10, though I'm not sure if automation can/should deal with those
# sorts of numbers

ardana_qe_test_venv_requires:
  - 'python-subunit'

#ardana_qe_test_get_results_cmds: 
 #ran:    "cat {{ ardana_qe_test_log }} | grep 'ATTEMPTING TO #REMOVE COMPUTE NODE' | wc -l"
 #failed: "cat {{ ardana_qe_test_log }} | grep 'FAIL' | wc -l"
 #passed: "cat {{ ardana_qe_test_log }} | grep 'PASS' | wc -l"
ardana_qe_test_get_failed_cmd: "grep -A 6 'FAIL' {{ ardana_qe_test_log }} || echo 'None'"

type_of_compute: COMPUTE
