#!/bin/sh
n=$1
cloudsource=$2
if [ -z "$n" ] ; then
	echo "usage: $0 crowbard3 develcloud6"
	exit 1
fi

if [[ "$n" != crowbard2 && "$n" != crowbard3 ]] ; then
	echo "bad VM name"
	exit 2
fi

virsh destroy $n

echo "cloudsource=$cloudsource"
rm -f mkcloud.config
: ${cachedir:=/tmp}
export mkclouddriver=libvirt
SCRIPTS_DIR=/usr/src/automation/scripts
scripts_lib_dir=${SCRIPTS_DIR}/lib
common_scripts="mkcloud-onhost.sh mkcloud-common.sh mkcloud-$mkclouddriver.sh"
for script in $common_scripts; do
    source ${scripts_lib_dir}/$script
done
admin_node_disk=/dev/system/$n
onhost_prepareadmin
virsh start $n
sleep 100 # time for the admin VM to boot
sshkey=`cat ~/.ssh/id_rsa.pub`
ssh_password $n "echo '$sshkey' >> ~/.ssh/authorized_keys"

