#!/bin/sh
[ "$UID" = 0 ] || exec sudo $0 "$@" || exit 52
n=$1
cloudsource=$2
if [ -z "$n" ] ; then
        echo "usage: $0 crowbard3 develcloud6"
        exit 1
fi

if [[ "$n" != crowbarp2 ]] ; then
        echo "bad VM name"
        exit 2
fi

virsh destroy $n
virsh undefine $n

echo "cloudsource=$cloudsource"
rm -f mkcloud.config
: ${cachedir:=/root/tmp}
mkdir -p $cachedir
export mkclouddriver=libvirt
SCRIPTS_DIR=/usr/src/automation/scripts
scripts_lib_dir=${SCRIPTS_DIR}/lib
common_scripts="mkcloud-onhost.sh mkcloud-common.sh mkcloud-$mkclouddriver.sh"
for script in $common_scripts; do
    source ${scripts_lib_dir}/$script
done
admin_node_disk=/dev/system/$n
[ -e $admin_node_disk ] || admin_node_disk=/dev/gate/$n
[ -e $admin_node_disk ] || exit 51
onhost_prepareadmin
virsh define $SCRIPTS_DIR/../hostscripts/gatehost/$n.xml # is OK to fail if already there
virsh start $n
sleep 100 # time for the admin VM to boot
sshkey=`cat /root/.ssh/id_rsa.pub`
ssh_password $n.cloud.suse.de. "mkdir -p ~/.ssh ; echo '$sshkey' >> ~/.ssh/authorized_keys"

