#!/bin/sh
n=$1
if [ -z "$n" ] ; then
    echo "usage: $0 <vmname> [ flavor ]"
    exit 1
fi

if [[ "$n" != cleanvm ]] ; then
    echo "bad VM name"
    exit 2
fi

flavor=$2

p=/mnt/ssd/images/

if ! [ -f $p/$flavor.img -o -f $p/$flavor.qcow2 ]; then
    echo "Bad Flavor name: \"$flavor\""
    exit 2
fi

virsh destroy $n
if [ "$n" = "cleanvm" ] ; then
    dd if=/dev/zero of=/dev/vg0/$n-data count=16
    if [ -e $p/$flavor.qcow2 ] ; then
        time qemu-img convert $p/$flavor.qcow2 /dev/vg0/$n
    else
        time dd if=$p/$flavor.img of=/dev/vg0/$n bs=64k
    fi
else
    gzip -cd $p/$n.img.gz > /dev/vg0/$n
fi
setfacl -m jenkins:r "/dev/vg0/$n"
virsh start "$n"

