#!/bin/sh
n=$1
shift
[ -z "$n" ] && echo usage: "$0 NUM" && exit 55
if [ $n -lt 1 -o $n -gt 39 ] ; then
  echo "$n out of range"
  exit 56
fi

# workaround libvirtd disappearance:
pidof libvirtd || /usr/local/sbin/fixlibvirt
. /root/cloud.d/cloudfunc

export cloudvg=mkcvg0
#export cloudsource=GM2.0
#export TESTHEAD=1
#export cephvolumenumber=1
#export libvirt_type=xen
#export networkingplugin=linuxbridge
#export forwardmode="route"
#export NOQACROWBARDOWNLOAD=1
export net_admin=$(cloudadminnet $n)
export net_public=$(cloudpublicnet $n)
export adminnetmask=255.255.254.0
export virtualcloud=$vcloudname$n
export cloud=$virtualcloud
#exec bash -x ./mkcloud "$@"

