#!/usr/bin/env python

import argparse

import libvirt_setup


def main():

    parser = argparse.ArgumentParser(description="Cleanup libvirt resources.")
    parser.add_argument("cloud", type=str, help="Name of the Cloud")
    parser.add_argument("nodenumber", type=int, help="Number of Nodes")
    parser.add_argument("cloudbr", type=str, help="Name of the Virtual Bridge")
    parser.add_argument("public_vlan", type=str,
                        help="ID of the Public VLAN")

    args = parser.parse_args()

    libvirt_setup.cleanup(args)

if __name__ == "__main__":
    main()
