#!/usr/bin/env python
import argparse
import os

import libvirt_setup


def main():
    parser = argparse.ArgumentParser(description="Create Compute Node Config.")
    parser.add_argument("cloud", help="Name of the Cloud")
    parser.add_argument("nodecounter", type=int,
                        help="Node Counter \
                        (when this script is called within a loop, this \
                        is usually an incremented number)")
    parser.add_argument("macaddress", help="MAC Address")
    parser.add_argument("raid_volumes", type=int,
                        help="Number of disks for RAID on node")
    parser.add_argument("cephvolumenumber", type=int,
                        help="Number of Ceph Volumes")
    parser.add_argument("drbdserial", help="DRBD Volume Serial")
    parser.add_argument("nodememory", type=int,
                        help="Node Memory (kB)")
    parser.add_argument("libvirttype", help="Libvirt Type (e.g. kvm)")
    parser.add_argument("vcpus", type=int, help="Number of VCPUs")
    parser.add_argument("emulator", help="QEMU to use",
                        default="/usr/bin/qemu-system-%s" % os.uname()[4])
    parser.add_argument("vdiskdir",
                        help="Virtual Disk Directory (e.g /dev/cloud)")
    parser.add_argument("bootorder", type=int, help="Boot Order (e.g. 2)")
    parser.add_argument("firmwaretype", default="bios",
                        help="Boot firmware type for the node")
    args = parser.parse_args()

    print(libvirt_setup.compute_config(args, libvirt_setup.cpuflags()))


if __name__ == "__main__":
    main()
