#!/usr/bin/env python
import argparse

import libvirt_setup


def main():
    parser = argparse.ArgumentParser(description="Start a Virtual Network")
    parser.add_argument("netpath", help="Path to the network XML")
    args = parser.parse_args()

    libvirt_setup.net_start(args)


if __name__ == "__main__":
    main()
