#!/usr/bin/env python
import argparse

import libvirt_setup


def main():
    parser = argparse.ArgumentParser(description="Create Admin Network Config")
    parser.add_argument("cloud", help="Name of the Cloud")
    parser.add_argument("cloudbr", help="Name of the Virtual bridge")
    parser.add_argument("admingw", help="IP Address of the Admin Gateway")
    parser.add_argument("adminnetmask", help="Netmask of the Admin Network")
    parser.add_argument("cloudfqdn", help="Name of the Cloud-FQDN")
    parser.add_argument("adminip", help="IP Address of the Admin Node")
    parser.add_argument("forwardmode", help="Forward Mode (e.g. nat)")
    args = parser.parse_args()

    print(libvirt_setup.net_config(args))


if __name__ == "__main__":
    main()
