#!/usr/bin/env python

import argparse

import libvirt_setup


def main():

    parser = argparse.ArgumentParser(description="Create Admin Network Config")
    parser.add_argument("cloud", type=str, help="Name of the Cloud")
    parser.add_argument("cloudbr", type=str, help="Name of the Virtual bridge")
    parser.add_argument("admingw", type=str,
                        help="IP Address of the Admin Gateway")
    parser.add_argument("adminnetmask", type=str,
                        help="Netmask of the Admin Network")
    parser.add_argument("cloudfqdn", type=str, help="Name of the Cloud-FQDN")
    parser.add_argument("adminip", type=str,
                        help="IP Address of the Admin Node")
    parser.add_argument("forwardmode", type=str,
                        help="Forward Mode (e.g. nat)")

    args = parser.parse_args()

    print(libvirt_setup.net_config(args))

if __name__ == "__main__":
    main()
