#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Limited to the deployer
---

- name: deployer-rhel-repo | create_target_repo_tarball | Ensure all rpms
        directory exists
  file:
    path: "{{ centos_rpms_workdir }}/{{ centos_all_rpms_dir }}"
    state: directory

- name: deployer-rhel-repo | create_target_repo_tarball | Create repomd yum repo
        for centos rpms
  command: createrepo {{ centos_rpms_workdir }}/{{ centos_all_rpms_dir }}
  register: _rpms_workdir_createrepo_result

- name: deployer-rhel-repo | create_target_repo_tarball | Create updated new rpms tarball
  command: tar -cvzf {{ centos_repo_tarball_name }} {{ centos_all_rpms_dir }}
  args:
    chdir: "{{ centos_rpms_workdir }}"
  register: _rpms_workdir_tarball_result
  when: _rpms_workdir_createrepo_result | success

- name: deployer-rhel-repo | create_target_repo_tarball | Move tarball to expected
        location
  copy:
    src: "{{ centos_rpms_workdir }}/{{ centos_repo_tarball_name }}"
    dest: "{{ ardanauser_home }}/{{ centos_repo_tarball_name }}"
  when: _rpms_workdir_tarball_result | success
