#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

heat_resource_name_prefix: "{{ cloud_env }}-cloud"
rhel_distro_id: "rhel{{ rhel_os_version }}-x86_64"
rhel_image: "centos{{ rhel_os_version }}"
# If SES is disabled, we need a greater disk size for swift
disk_size: "{{ ses_enabled | ternary(2, 3) }}"

# Versioned virtualized configuration artifacts
virt_artifacts:
  cloud7:
    sles_distro_id: sles12sp2-x86_64
    rhel_distro_id:
    sles_image: "{{ vcloud_image_name_prefix }}-SLE12SP2"
    rhel_image:
    clm_flavor: cloud-ardana-job-compute
    controller_flavor: cloud-ardana-job-controller
    compute_flavor: cloud-ardana-job-compute
  cloud8:
    sles_distro_id: sles12sp3-x86_64
    rhel_distro_id: "{{ rhel_distro_id }}"
    sles_image: "{{ vcloud_image_name_prefix }}-SLE12SP3"
    rhel_image: "{{ rhel_image }}"
    clm_flavor: cloud-ardana-job-compute
    controller_flavor: cloud-ardana-job-controller
    compute_flavor: cloud-ardana-job-compute
  cloud9:
    sles_distro_id: sles12sp4-x86_64
    rhel_distro_id: "{{ rhel_distro_id }}"
    sles_image: "{{ vcloud_image_name_prefix }}-SLE12SP4"
    rhel_image: "{{ rhel_image }}"
    clm_flavor: cloud-ardana-job-compute
    controller_flavor: cloud-ardana-job-controller
    compute_flavor: cloud-ardana-job-compute

# Exhaustive list of service components required by the CLM node.
# When service components that are not in this list are hosted
# by an Ardana node, that node is considered either a controller node
# or a compute node
clm_service_components:
  - lifecycle-manager
  - tempest
  - openstack-client
  - ceilometer-client
  - cinder-client
  - designate-client
  - glance-client
  - heat-client
  - ironic-client
  - keystone-client
  - magnum-client
  - manila-client
  - neutron-client
  - nova-client
  - swift-client
  - monasca-client
  - barbican-client
  - octavia-client
  - ntp-client

virt_config:
  sles_distro_id: '{{ virt_artifacts[cloud_release].sles_distro_id }}'
  rhel_distro_id: '{{ virt_artifacts[cloud_release].rhel_distro_id }}'
  clm_service_components: '{{ clm_service_components }}'
  clm_flavor: '{{ clm_flavor|default(virt_artifacts[cloud_release].clm_flavor) }}'
  controller_flavor: '{{ controller_flavor|default(virt_artifacts[cloud_release].controller_flavor) }}'
  compute_flavor: '{{ compute_flavor|default(virt_artifacts[cloud_release].compute_flavor) }}'
  sles_image: '{{ sles_image|default(virt_artifacts[cloud_release].sles_image) }}'
  rhel_image: '{{ rhel_image|default(virt_artifacts[cloud_release].rhel_image) }}'
  disk_size: '{{ disk_size }}'
  flavors: '{{ flavors|default([]) }}'
  images: '{{ images|default([]) }}'
  disks: '{{ disks|default([]) }}'
