#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Check if subunit2sql installed
  stat:
    path: "{{ subunit2sql_bin }}"
  register: _subunit2sql

- include_tasks: install_subunit2sql.yml
  when: not _subunit2sql.stat.exists

- name: Gather variables for '{{ task }}'
  include_vars: "{{ task }}.yml"

- name: Get cloud media build version
  command: "awk '/Media build version/ { print $4 }' /etc/motd"
  register: cloud_media_build_version
  when: "'stdout' not in cloud_media_build_version"

- name: Send results to OpenStack-Health
  command: |
    {{ subunit2sql_venv }}/bin/subunit2sql --database-connection mysql+pymysql://subunit:subunit@{{ os_health_server }}/subunit \
      --run_meta "{{ os_health_metadata | join(',') }}" --artifacts "{{ jenkins_artifacts_url }}" {{ test_results_subunit }}
  changed_when: false

# NOTE: Removing SLE-SDK repos and packages required for subunit2sql
# as they were affecting maintenance updates
- include_tasks: os_health_requires.yml
  vars:
    os_health_requires_state: "absent"
  when: not _subunit2sql.stat.exists
