#!/bin/bash
r=/srv/nfs/repos/

# disable/debug rsync with E=echo
E=echo
E=

# disable/debug {u,}mount with M=echo
M=echo
M=

# debug/test rsync with DRY=--dry-run
DRY=--dry-run
DRY=

rsync="$E rsync $DRY --bwlimit 10000 --delay-updates --delete-delay -avH --no-owner --no-group --exclude=*src.rpm "

# http://download.suse.de/ibs/Devel:/Cloud:/4/images/*qcow2 -> images/SLES11-SP3-x86_64-cfntools.qcow2

buildsuse=/mnt/dist/ibs/
buildncc=$buildsuse
ibsmaint=$buildsuse/SUSE\:/Maintenance\:/Test\:/

##############
# SLE 12
##############

for servicepack in 1 2 3; do
    # fetch latest code from service pack in development (not just latest beta)
    sync_from_ibs=
    [ $servicepack -eq 3 ] && sync_from_ibs=1

    version="12-SP$servicepack"
    repo_version="$version"
    chef_version="12.$servicepack"

    for arch in x86_64 s390x aarch64; do
        # only x86_64 for SP0
        [ "$arch" != x86_64 -a $servicepack -eq 0 ] && continue
        [ "$arch" = "aarch64" -a $servicepack -eq 1 ] && continue
        install_subdir="/$arch"
        # no subdir for /install for SP0
        [ $servicepack -eq 0 ] && install_subdir=

        echo ================== Updating SLE 12 SP$servicepack for $arch

        destdir=/srv/nfs/suse-${chef_version}${install_subdir}/install/
        mkdir -p $destdir
        if test -d /mnt/dist/install/SLP/SLE-$version-Server-GM/$arch/DVD1/ ; then
            $rsync /mnt/dist/install/SLP/SLE-$version-Server-GM/$arch/DVD1/ $destdir
        else
            $rsync /mnt/dist/install/SLP/SLE-$version-Server-TEST/$arch/DVD1/ $destdir
        fi

        # SLES pool
        if [ -z "$sync_from_ibs" ]; then
            $rsync --link-dest /srv/nfs/suse-${chef_version}${install_subdir}/install/suse/ $buildsuse/SUSE/Products/SLE-SERVER/$version/$arch/product/ /srv/nfs/repos/$arch/SLES$repo_version-Pool/
        else
            $rsync --link-dest /srv/nfs/suse-${chef_version}${install_subdir}/install/suse/ /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-Server-POOL-$arch-Media1/ /srv/nfs/repos/$arch/SLES$repo_version-Pool/
        fi
        # SLES updates
        $rsync $buildsuse/SUSE/Updates/SLE-SERVER/$version/$arch/update/ /srv/nfs/repos/$arch/SLES$repo_version-Updates/
        # SLES test updates
        if test -d $ibsmaint/SLE-SERVER\:/$version\:/$arch/update/ ; then
            $rsync $ibsmaint/SLE-SERVER\:/$version\:/$arch/update/ /srv/nfs/repos/$arch/SLES$repo_version-Updates-test/
        fi

        # HA is only for > SP1, and not for ARM
        if [ $servicepack -gt 0 -a "$arch" != aarch64 ]; then
            # HA pool
            if [ -z "$sync_from_ibs" ]; then
                $rsync $buildsuse/SUSE/Products/SLE-HA/$version/$arch/product/ /srv/nfs/repos/$arch/SLE$repo_version-HA-Pool/
            else
                $rsync /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-HA-POOL-$arch-Media1/ /srv/nfs/repos/$arch/SLE$repo_version-HA-Pool/
            fi
            # HA updates
            $rsync $buildsuse/SUSE/Updates/SLE-HA/$version/$arch/update/ /srv/nfs/repos/$arch/SLE$repo_version-HA-Updates/
            # HA test updates
            if test -d $ibsmaint/SLE-HA\:/$version\:/$arch/update/ ; then
                $rsync $ibsmaint/SLE-HA\:/$version\:/$arch/update/ /srv/nfs/repos/$arch/SLE$repo_version-HA-Updates-test/
            fi
        fi

        # SDK is only for > SP1, and not for ARM
        if [ $servicepack -gt 0 -a "$arch" != aarch64 ]; then
            # SDK pool
            if [ -z "$sync_from_ibs" ]; then
                $rsync $buildsuse/SUSE/Products/SLE-SDK/$version/$arch/product/ /srv/nfs/repos/$arch/SLE$repo_version-SDK-Pool/
            else
                $rsync /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-SDK-POOL-$arch-Media1/ /srv/nfs/repos/$arch/SLE$repo_version-SDK-Pool/
            fi
            # SDK updates
            $rsync $buildsuse/SUSE/Updates/SLE-SDK/$version/$arch/update/ /srv/nfs/repos/$arch/SLE$repo_version-SDK-Updates/
            # SDK test updates
            if test -d $ibsmaint/SLE-SDK\:/$version\:/$arch/update/ ; then
                $rsync $ibsmaint/SLE-SDK\:/$version\:/$arch/update/ /srv/nfs/repos/$arch/SLE$repo_version-SDK-Updates-test/
            fi
        fi
    done
done


##############
# Storage
##############

for version in 2.1 4 5; do

    for arch in x86_64 aarch64; do
        [ "$arch" != x86_64 -a $version = 2.1 ] && continue

        echo ================== Updating Storage $version

        # sync version 4 from ibs while in development
        poolsource=
        if [[ $version == 4 ]]; then
            poolsource=/mnt/dist/ibs/SUSE\:/SLE-12-SP2\:/Update\:/Products\:/SES${version}/images/repo/SUSE-Enterprise-Storage-${version}-POOL-${arch}-Media1/
        else
            poolsource=$buildsuse/SUSE/Products/Storage/$version/$arch/product/
        fi
        $rsync $poolsource /srv/nfs/repos/$arch/SUSE-Enterprise-Storage-$version-Pool

        if test -d $buildsuse/SUSE/Updates/Storage/$version/$arch/update/; then
            $rsync $buildsuse/SUSE/Updates/Storage/$version/$arch/update/ /srv/nfs/repos/$arch/SUSE-Enterprise-Storage-$version-Updates
        fi

        if test -d $ibsmaint/Storage\:/$version\:/$arch/update/; then
            $rsync $ibsmaint/Storage\:/$version\:/$arch/update/ /srv/nfs/repos/$arch/SUSE-Enterprise-Storage-$version-Updates-test
        fi
    done
done


##############
# Cloud
##############

function mount_and_rsync {
    local from=$1
    local to=$2
    local oneiso=`ls $from | tail -1`
    if [ -e "$oneiso" ] ; then
        $M mount -o loop,ro "$oneiso" /mnt/cloud
        [ $? == 0 ] && $rsync /mnt/cloud/ /srv/nfs/repos/$to/
        $M umount /mnt/cloud
    fi
}

# mirror aarch64 SP1 builds
$rsync /mnt/dist/ibs/Devel:/ARM:/SLE-12-SP1:/Update/images/repo/SLE-12-SP1-Server-POOL-aarch64-*-Media1/ /srv/nfs/repos/aarch64/SLES12-SP1-Pool

for version in 6 7 8; do
    # fetch latest code from version in development (not just latest beta)
    sync_from_ibs=
    [ "$version" == "8" ] && sync_from_ibs=1
    servicepack=1
    [ "$version" == "7" ] && servicepack=2

    for arch in x86_64 s390x aarch64; do
        # no ARM for Cloud <= 6
        [ "$arch" == aarch64 -a $version -le 6 ] && continue

        echo ================== Updating Cloud $version for $arch

        if [ -z "$sync_from_ibs" ]; then
            $rsync /mnt/dist/install/SLP/SLE-12-SP$servicepack-Cloud$version-GM/$arch/DVD1/ /srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-official
        else
            mount_and_rsync "/mnt/dist/ibs/SUSE:/SLE-12-SP$servicepack:/Update:/Products:/Cloud$version/images/iso/SUSE-OPENSTACK-CLOUD-$version-$arch-Build[0-9][0-9][0-9][0-9]-Media1.iso" $arch/SUSE-OpenStack-Cloud-$version-official
        fi

        mount_and_rsync "/mnt/dist/ibs/Devel\:/Cloud\:/$version/images/iso/SUSE-OPENSTACK-CLOUD-$version-$arch-Build[0-9][0-9][0-9][0-9]-Media1.iso" $arch/SUSE-OpenStack-Cloud-$version-devel
        mount_and_rsync "/mnt/dist/ibs/Devel\:/Cloud\:/$version\:/Staging/images/iso/SUSE-OPENSTACK-CLOUD-$version-$arch-Build[0-9][0-9][0-9][0-9]-Media1.iso" $arch/SUSE-OpenStack-Cloud-$version-devel-staging

        if test -d $buildsuse/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ ; then
            $rsync $buildsuse/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ /srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-Pool/
        fi

        if test -d $buildsuse/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ ; then
            $rsync $buildsuse/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ /srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-Updates/
        fi

        if test -d $ibsmaint/OpenStack-Cloud\:/$version\:/$arch/update/; then
            $rsync $ibsmaint/OpenStack-Cloud\:/$version\:/$arch/update/ /srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-Updates-test/
        fi
    done
done

# sync admin images
for arch in x86_64 aarch64 s390x ; do
    $rsync -L /mnt/dist/ibs/Devel:/Cloud:/Images/images_SLE_12_SP2/mkcloud-admin-node-SLE12SP2.${arch}.qcow2 /srv/nfs/images/$arch/SLES12-SP2-untested.qcow2

    $rsync -L /mnt/dist/ibs/Devel:/Cloud:/Images/images_SLE_12_SP3/mkcloud-admin-node-SLE12SP3.${arch}.qcow2 /srv/nfs/images/$arch/SLES12-SP3-untested.qcow2

    if [ "$arch" == x86_64 ]; then
        $rsync -L /mnt/dist/ibs/Devel:/Cloud:/Images/images_SLE_12_SP2/mkcloud-admin-node-SLE12SP2-uefi.${arch}.qcow2 /srv/nfs/images/$arch/SLES12-SP2-uefi.qcow2
    fi
done

# reduce disk usage
fdupes -q -n -r /srv/nfs/repos/ /srv/nfs/install/ |
    while read _file; do
        if test -z "$_target" ; then
            _target="$_file";
        else
            if test -z "$_file" ; then
                _target="";
                continue ;
            fi
            ln -f "$_target" "$_file";
        fi
     done

~/bin/syncgitrepos
