---
core_nodes: 2
lmm_nodes: "{{ (cloud_product == 'ardana') | ternary(3, 1) }}"
dbmq_nodes: 3
computes: 1
rhel_computes: 0

scenario:
  name: entry-scale-kvm-mml
  cloud_name: entry-scale-kvm-mml
  description: >
    Multi-cluster scenario with all services enabled, {{ clm_model }} CLM node, {{ core_nodes }} OpenStack core nodes,
    {{ dbmq_nodes }} database nodes, {{ lmm_nodes }} LMM nodes, {{ computes }} SLES compute nodes and
    {{ rhel_computes }} RHEL compute nodes.
  audit_enabled: False
  ses_enabled: "{{ ses_enabled | default(False) }}"
  availability_zones: "{{ availability_zones }}"
  use_cinder_volume_disk: False
  use_glance_cache_disk: False


  service_template: mml-core
  network_template: "{{ (cloud_product == 'ardana') | ternary('compact', 'crowbar') }}"
  interface_template: "{{ (cloud_product == 'ardana') | ternary('mml-core', 'crowbar') }}"

