---
  product:
    version: 2

  firewall-rules:

    - name: PING
      network-groups:
      - MANAGEMENT
      rules:
      - type: allow
        remote-ip-prefix:  0.0.0.0/0
        port-range-min: 8
        port-range-max: 0
        protocol: icmp

    - name: NETCAT
      network-groups:
      - MANAGEMENT
      rules:
      - type: allow
        remote-ip-prefix:  0.0.0.0/0
        port-range-min: 11382
        port-range-max: 11382
        protocol: tcp
