#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

rhel_release: '7.5'

cloud_version: 8

yum_optional_loc: ardana/rhel7/yum/optional
yum_optional_dir: "{{ PACKAGE_CONSTANTS.REPO_DIR }}/{{ yum_optional_loc }}"

# Centos qemu-kvm rpms tarball which meets nova qemu-kvm pike version
# requirement. This is intended to be used only for internal testing.
# Customer is expected to use these rpms via their RHEL subscription repos.
deployer_rhel7_yum_optional_tarball: "rhel7-opt-yum.tgz"

disable_suse_centos_repo_auto_setup: false

_downloaded_rpms_list: []

centos_repo_setup_name: "centos_c{{ cloud_version }}_ardana"
centos_repo_setup_url: "https://download.opensuse.org/repositories/systemsmanagement:/Ardana:/{{ cloud_version }}:/CentOS:/{{ rhel_release }}/CentOS_{{ rhel_release }}/"

centos_all_rpms_dir: all_rpms
centos_repo_tarball_name: centos_rpms_repo.tgz

# If user has defined centos repo beforehand, provide repo alias name here
# In that case, that repo is used to download artifacts
centos_repository_name: ''
centos_downloaded_rpms_dir: ''

env_yum_optional_tarball_location: "{{ lookup('env', 'ARDANA_RHEL_OPTIONAL_TARBALL_LOCATION') | default('', true) }}"

rhel_optional_repo_enabled: "{{ lookup('env', 'ARDANA_RHEL_OPTIONAL_REPO_ENABLED') | default(True, true) | bool }}"


# List of venv rpms to be installed on deployer
rhel_venv_rpms_list:
  - venv-openstack-nova-rhel-x86_64
  - venv-openstack-neutron-rhel-x86_64
  - venv-openstack-monasca_agent-rhel-x86_64

# List of rhel/centos rpms to be made available for RHEL compute. These rpms
# are hosted on deployer and accordingly repo is configured on RHEL compute.
# The RPMs come from the cloud CentOS zypper repository [1] and they are copied
# over to the deployer to a location which is set up as a CentOS yum repository.
#
# FIXME: maintaining this list is a real pain, because every time package
# dependencies change, it needs to be updated. A better way to do this would
# be to follow the approach in the official documentation [2] which is to
# store the full contents of the CentOS zypper repository on the deployer,
# instead of downloading only the packages in this list. This also requires
# the repository contents to be mirrored to Provo.
#
# [1] https://download.opensuse.org/repositories/systemsmanagement:/Ardana:/[8|9]:/CentOS:/[7.3|7.5]/CentOS_[7.3|7.5/
# [2] http://docserv.suse.de/documents/SUSE_OpenStack_Cloud_8/hpe-helion-openstack-installation/single-html/#sec.install_rhel_compute_node.provision-deployer
rhel_repo_rpms_list:
  - ca-certificates-mozilla
  - python-asn1crypto
  - python-Babel
  - python-PyJWT
  - python-appdirs
  - python-blinker
  - python-certifi
  - python-cffi
  - python-conf_d
  - python-debtcollector
  - python-dogpile.cache
  - python-ecdsa
  - python-enum34
  - python-funcsigs
  - python-glob2
  - python-idna
  - python-ipaddress
  - python-iso8601
  - python-keystoneauth1
  - python-keystoneclient
  - python-monotonic
  - python-msgpack-python
  - python-netaddr
  - python-netifaces
  - python-oauthlib
  - python-oslo.config
  - python-oslo.i18n
  - python-oslo.serialization
  - python-oslo.utils
  - python-pbr
  - python-ply
  - python-positional
  - python-py
  - python-pycparser
  - python-pykerberos
  - python-pytz
  - python-requests
  - python-requests-kerberos
  - python-rfc3986
  - python-setuptools
  - python-stevedore
  - python-urllib3
  - python-wrapt
  - python-cryptography
  - python-base
  - python-Beaver
  - python-pyparsing
  - python-packaging
  - python-PyYAML
  - python-xml
  - python-chardet
  - python-ardana-packager
  - openvswitch
  - python-psutil
  - python-PyNaCl
  - python-bcrypt
  - python-paramiko
  - python-functools32
  - python-jsonschema
  - python-jsonpatch
  - python-warlock
  - python-pyOpenSSL
  - python-glanceclient
  - python-PrettyTable
  - python-novaclient
  - python-os-client-config
  - python-osprofiler
  - python-osc-lib
  - python-neutronclient
  - python-swiftclient
  - python-pycrypto
  - python-futures
  - python-tzlocal
  - python-APScheduler
  - netcfg
  - python-enum-compat
  - python-eventlet
  - python-retrying
  - python-os-win
  - python-oslo.privsep
  - python-oslo.policy
  - python-castellan
  - python-fasteners
  - python-oslo.concurrency
  - python-os-brick
  - python-pyperclip
  - python-cmd2
  - python-unicodecsv
  - python-cliff
  - python-freezerclient
  - python-docutils
  - python-python-dateutil
  - python-jmespath
  - python-botocore
  - python-PyMySQL
  - python-PasteDeploy
  - python-repoze.lru
  - python-Routes
  - python-greenlet
  - python-WebOb
  - python-requestsexceptions
  - python-Paste
  - python-oslo.service
  - python-pymongo
  - python-pyinotify
  - python-oslo.context
  - python-oslo.log
  - python-simplejson
  - python-cinderclient
  - python-freezer
  - openstack-freezer
  - openstack-freezer-agent
  - openstack-freezer-api
  - openstack-freezer-scheduler
  - python-python-logstash
  - python-monascaclient
  - supportutils
  - supportutils-plugin-suse-openstack-cloud
  # The following are required only for SOC9
  - python-six
  - python-openstacksdk
  - python-os-service-types
  - python-msgpack
  - python-wcwidth
  - python-contextlib2
  - python-subprocess32
  - python-deprecation
  - python-munch
  - libsodium23
  - python-PySocks
