#!/bin/bash

#
# update the automation scripts on jenkins nodes
# it will pull the latest changes from the git repo
# and update the symlinks in ~/bin for the wanted scripts
#
# it can be called from within the jenkins job itself
#
# Usage: update_automation [<scriptname>, ...]
#
# J. Daniel Schmidt <jdsn@suse.de>
#

automation_repo="git://github.com/SUSE-Cloud/automation.git"

pushd ~ > /dev/null
a_dir=${automation_repo#*git://}
a_dir=${a_dir%.git}
p_dir=${a_dir%/*}

function do_wget
{
    wget -Omaster.tar.gz https://${a_dir}/archive/master.tar.gz
    tar xzf master.tar.gz
    mkdir -p $p_dir
    rm -rf $a_dir
    mv automation-master $a_dir
    exit 0
}

rpm -q git-core || zypper --non-interactive in git-core || do_wget

if [ -d $a_dir ] ; then
    pushd $a_dir > /dev/null
        git clean -f
        git checkout master
        git fetch origin
        git reset --hard origin/master
    popd > /dev/null
else
    mkdir -p $p_dir
    pushd $p_dir > /dev/null
        git clone ${automation_repo}
    popd > /dev/null
fi

popd > /dev/null
