---

interface_models:
  - name: ALL
    service_groups:
      - admin
      - clm
      - controller
      - compute
      - core
      - lmm
      - dbmq
      - neutron
      - swpac
      - swobj
      - swift
    network_interfaces:
{% if bootstrap_network %}
      - network_groups:
          - BOOTSTRAP
{% endif %}
      - network_groups:
          - MANAGEMENT
          - PUBLIC
          - OS_SDN
          - STORAGE
